const C=window.DXN_CONFIG||{};
const ready=Boolean(C.SUPABASE_ANON_KEY&&!C.SUPABASE_ANON_KEY.startsWith("PUT_"));
const db=ready?supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
let lang=localStorage.getItem("dxn_lang")||"ar",member=null,isAdmin=false;
const tr={ar:{login:"تسجيل الدخول",register:"إنشاء حساب",name:"الاسم الكامل",age:"العمر",wa:"رقم WhatsApp",id:"رقم عضوية DXN",email:"البريد الإلكتروني",password:"كلمة المرور",city:"المدينة",goal:"ما هدفك الأساسي من الانضمام؟",time:"ما الوقت الذي يمكنك تخصيصه بانتظام لتطوير مشروعك؟",learn:"ما الذي تريد أن تتعلمه أولًا؟",ready:"هل أنت مستعد لتطبيق ما تتعلمه؟",start:"متى تستطيع البدء؟",contact:"ما أفضل وقت للتواصل معك عبر WhatsApp؟",enter:"دخول",create:"إنشاء الحساب",switchReg:"إنشاء حساب جديد",switchLogin:"لدي حساب بالفعل",welcome:"مرحبًا بك في فريق DXN 🇲🇷",intro:"هذا النموذج يساعدنا على معرفة هدفك واحتياجاتك حتى نوجهك إلى التدريب والخطوات المناسبة لك. يستغرق حوالي دقيقتين.",training:"التدريب",tasks:"المهام",points:"النقاط",progress:"التقدم",profile:"ملفي",admin:"المسؤول",save:"حفظ",done:"تم الإنجاز",open:"فتح",logout:"خروج",config:"أضف Publishable/anon key في config.js أولًا.",success:"تم الحفظ بنجاح",no:"لا توجد بيانات.",search:"بحث بالاسم / العضوية / WhatsApp"},
fr:{login:"Connexion",register:"Créer un compte",name:"Nom complet",age:"L’âge",wa:"Numéro WhatsApp",id:"Numéro de membre DXN",email:"Adresse e-mail",password:"Mot de passe",city:"Ville",goal:"Quel est votre objectif principal en rejoignant DXN ?",time:"Quel temps pouvez-vous consacrer régulièrement au développement de votre activité ?",learn:"Que souhaitez-vous apprendre en premier ?",ready:"Êtes-vous prêt(e) à mettre en pratique ce que vous apprenez ?",start:"Quand pouvez-vous commencer ?",contact:"Quel est le meilleur moment pour vous contacter sur WhatsApp ?",enter:"Connexion",create:"Créer le compte",switchReg:"Créer un nouveau compte",switchLogin:"J’ai déjà un compte",welcome:"Bienvenue dans l’équipe DXN 🇲🇷",intro:"Ce formulaire nous permet de connaître votre objectif et vos besoins afin de vous orienter vers la formation adaptée. Il prend environ 2 minutes.",training:"Formation",tasks:"Tâches",points:"Points",progress:"Progression",profile:"Mon profil",admin:"Administration",save:"Enregistrer",done:"Terminé",open:"Ouvrir",logout:"Déconnexion",config:"Ajoutez d’abord la clé Publishable/anon dans config.js.",success:"Enregistré",no:"Aucune donnée.",search:"Rechercher par nom / membre / WhatsApp"}};
const opts={
goal:[["استخدام المنتجات","Utiliser les produits"],["دخل إضافي","Avoir un revenu supplémentaire"],["بناء مشروع","Construire un business"],["بناء فريق وقيادة","Construire une équipe et développer le leadership"],["ما زلت أستكشف الفرصة","Je découvre encore l’opportunité"]],
time:[["أقل من 30 دقيقة يوميًا","Moins de 30 minutes par jour"],["30 دقيقة إلى ساعة يوميًا","30 minutes à 1 heure par jour"],["ساعة إلى ساعتين يوميًا","1 à 2 heures par jour"],["أكثر من ساعتين يوميًا","Plus de 2 heures par jour"],["حسب وقتي وظروفي","Selon mon temps et mes disponibilités"]],
learn:[["فهم البزنس","Comprendre le business"],["المنتجات","Les produits"],["كيفية الاستقطاب","Comment prospecter"],["كيفية تقديم الفرصة","Comment présenter l’opportunité"],["التسويق عبر الهاتف ووسائل التواصل","Marketing par téléphone et réseaux sociaux"],["أريد أن أتعلم كل شيء خطوة بخطوة","Je veux tout apprendre étape par étape"]],
ready:[["نعم، مستعد","Oui, je suis prêt(e)"],["أحتاج بعض الوقت","J’ai besoin d’un peu de temps"],["لست متأكدًا بعد","Je ne suis pas encore sûr(e)"]],
start:[["اليوم","Aujourd’hui"],["خلال هذا الأسبوع","Cette semaine"],["خلال هذا الشهر","Ce mois-ci"],["لاحقًا","Plus tard"]],
contact:[["صباحًا","Le matin"],["ظهرًا","À midi"],["مساءً","Le soir"],["أي وقت","À tout moment"]]]};
const T=k=>tr[lang][k]||k;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(s){const e=document.querySelector("#toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2400)}
function setLang(){lang=lang==="ar"?"fr":"ar";localStorage.setItem("dxn_lang",lang);render()}
document.querySelector("#langBtn").onclick=setLang;
document.querySelector("#logoutBtn").onclick=async()=>{if(db)await db.auth.signOut();member=null;isAdmin=false;render()};
function select(k,value=""){return `<select id="${k}"><option value="">—</option>${opts[k].map(x=>`<option value="${esc(x[0])}"${value===x[0]?" selected":""}>${esc(lang==="ar"?x[0]:x[1])}</option>`).join("")}</select>`}
function auth(mode="login"){
document.querySelector("#screen").innerHTML=`<div class="container"><div class="card form"><div class="center"><h2>${T(mode)}</h2><p class="muted">${T("welcome")}<br>${T("intro")}</p></div>
${mode==="register"?`<div class="field"><label>${T("name")}</label><input id="name" required></div><div class="field"><label>${T("age")}</label><input id="age" type="number" min="13" max="100" required></div><div class="field"><label>${T("wa")}</label><input id="wa" required></div><div class="field"><label>${T("id")}</label><input id="dxnid" required></div><div class="field"><label>${T("city")}</label><input id="city"></div><div class="field"><label>${T("goal")}</label>${select("goal")}</div><div class="field"><label>${T("time")}</label>${select("time")}</div><div class="field"><label>${T("learn")}</label>${select("learn")}</div><div class="field"><label>${T("ready")}</label>${select("ready")}</div><div class="field"><label>${T("start")}</label>${select("start")}</div><div class="field"><label>${T("contact")}</label>${select("contact")}</div>`:""}
<div class="field"><label>${T("email")}</label><input id="email" type="email" required></div><div class="field"><label>${T("password")}</label><input id="password" type="password" minlength="6" required></div>
<button id="submit" class="btn">${mode==="login"?T("enter"):T("create")}</button><div class="center small" style="margin-top:13px"><button id="switch" class="btn alt">${mode==="login"?T("switchReg"):T("switchLogin")}</button></div></div></div>`;
document.querySelector("#switch").onclick=()=>auth(mode==="login"?"register":"login");
document.querySelector("#submit").onclick=async()=>{
if(!db){toast(T("config"));return}
try{
const emailEl=document.querySelector("#email"),passEl=document.querySelector("#password");
if(mode==="login"){const {error}=await db.auth.signInWithPassword({email:emailEl.value.trim(),password:passEl.value});if(error)throw error}
else{
const payload={full_name:document.querySelector("#name").value.trim(),whatsapp:document.querySelector("#wa").value.trim(),dxn_member_id:document.querySelector("#dxnid").value.trim(),city:document.querySelector("#city").value.trim(),goal:document.querySelector("#goal").value,daily_time:document.querySelector("#time").value};
const {data,error}=await db.auth.signUp({email:emailEl.value.trim(),password:passEl.value});if(error)throw error;
if(!data.user)throw new Error("Veuillez vérifier votre e-mail / يرجى تأكيد البريد الإلكتروني");
const {error:e}=await db.from("dxn_start_members").insert({...payload,auth_user_id:data.user.id});if(e)throw e;
}
await boot()
}catch(e){toast(e.message||"Error")}
}}
async function boot(){
if(!db){auth();return}
const {data:{session}}=await db.auth.getSession();
if(!session){document.querySelector("#logoutBtn").classList.add("hidden");auth();return}
document.querySelector("#logoutBtn").classList.remove("hidden");
const {data:m}=await db.from("dxn_start_members").select("*").eq("auth_user_id",session.user.id).maybeSingle();member=m;
const {data:a}=await db.from("dxn_start_admins").select("user_id").eq("user_id",session.user.id).maybeSingle();isAdmin=Boolean(a);
render()
}
async function dashboard(){
const [{data:ts},{data:ps},{data:pts}]=await Promise.all([db.from("dxn_start_training").select("*").eq("is_published",true).order("sort_order"),db.from("dxn_start_progress").select("training_id,completed").eq("member_id",member.id),db.from("dxn_start_points").select("points").eq("member_id",member.id)]);
const done=(ps||[]).filter(x=>x.completed).length,total=(ts||[]).length,pct=total?Math.round(done*100/total):0,totalPts=(pts||[]).reduce((s,x)=>s+(x.points||0),0);
document.querySelector("#screen").innerHTML=`<div class="container"><section class="hero"><h1>${T("welcome")}</h1><p>${esc(member.full_name)}</p></section><div class="grid"><div class="card">${T("points")}<div class="stat">${totalPts}</div></div><div class="card">${T("progress")}<div class="stat">${pct}%</div><div class="progress"><i style="width:${pct}%"></i></div></div><div class="card">${T("training")}<div class="stat">${done}/${total}</div></div></div><div class="tabs"><button class="tab active" data-x="training">${T("training")}</button><button class="tab" data-x="tasks">${T("tasks")}</button><button class="tab" data-x="profile">${T("profile")}</button>${isAdmin?`<button class="tab" data-x="admin">${T("admin")}</button>`:""}</div><div id="panel"></div></div>`;
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadTab(b.dataset.x)});loadTab("training")
}
async function loadTab(x){
const p=document.querySelector("#panel");
if(x==="training"){const {data:a}=await db.from("dxn_start_training").select("*").eq("is_published",true).order("sort_order");const {data:b}=await db.from("dxn_start_progress").select("training_id,completed").eq("member_id",member.id);const done=new Set((b||[]).filter(q=>q.completed).map(q=>q.training_id));p.innerHTML=`<div class="list">${(a||[]).map(q=>`<div class="item"><b>${esc(lang==="ar"?q.title_ar:q.title_fr)}</b><p class="small muted">${esc(lang==="ar"?q.description_ar:q.description_fr)}</p><div class="row">${q.video_url?`<a class="btn" target="_blank" href="${esc(q.video_url)}">${T("open")}</a>`:""}<button class="btn alt" onclick="finishTraining('${q.id}')">${done.has(q.id)?T("done"):T("done")}</button></div></div>`).join("")||T("no")}</div>`}
else if(x==="tasks"){const {data:a}=await db.from("dxn_start_tasks").select("*").eq("is_active",true).order("day_number");const {data:b}=await db.from("dxn_start_task_completions").select("task_id").eq("member_id",member.id);const done=new Set((b||[]).map(q=>q.task_id));p.innerHTML=`<div class="list">${(a||[]).map(q=>`<div class="item"><div class="row between"><b>${esc(lang==="ar"?q.title_ar:q.title_fr)}</b><span class="pill">+${q.points}</span></div><p class="small muted">${esc(lang==="ar"?q.description_ar:q.description_fr)}</p><button class="btn alt" onclick="finishTask('${q.id}',${q.points})">${done.has(q.id)?T("done"):T("done")}</button></div>`).join("")||T("no")}</div>`}
else if(x==="profile"){p.innerHTML=`<div class="card"><h3>${T("profile")}</h3><p><b>${T("name")}:</b> ${esc(member.full_name)}</p><p><b>${T("age")}:</b> ${esc(member.age||"—")}</p><p><b>${T("wa")}:</b> ${esc(member.whatsapp)}</p><p><b>${T("id")}:</b> ${esc(member.dxn_member_id)}</p><p><b>${T("city")}:</b> ${esc(member.city)}</p><div class="field"><label>${T("goal")}</label>${select("goal",member.goal||"")}</div><div class="field"><label>${T("time")}</label>${select("time",member.daily_time||"")}</div><button class="btn" onclick="saveProfile()">${T("save")}</button></div>`}
else if(x==="admin")await adminPanel(p)
}
window.finishTraining=async id=>{const {error}=await db.from("dxn_start_progress").upsert({member_id:member.id,training_id:id,completed:true,completed_at:new Date().toISOString()},{onConflict:"member_id,training_id"});if(error)toast(error.message);else{await db.from("dxn_start_points").insert({member_id:member.id,points:10,reason:"training_completed"});toast(T("success"));dashboard()}};
window.finishTask=async(id,points)=>{const {error}=await db.from("dxn_start_task_completions").upsert({member_id:member.id,task_id:id,completed_at:new Date().toISOString()},{onConflict:"member_id,task_id"});if(error)toast(error.message);else{await db.from("dxn_start_points").insert({member_id:member.id,points,reason:"task_completed"});toast(T("success"));dashboard()}};
window.saveProfile=async()=>{const {error}=await db.from("dxn_start_members").update({goal:document.querySelector("#goal").value,daily_time:document.querySelector("#time").value}).eq("id",member.id);if(error)toast(error.message);else{member.goal=document.querySelector("#goal").value;member.daily_time=document.querySelector("#time").value;toast(T("success"));dashboard()}};
async function adminPanel(p){const {data:m}=await db.from("dxn_start_members").select("*").order("created_at",{ascending:false});const all=m||[];p.innerHTML=`<div class="grid"><div class="card">الأعضاء<div class="stat">${all.length}</div></div><div class="card">نشطون<div class="stat">${all.filter(x=>x.status==="active").length}</div></div><div class="card">متابعة<div class="stat">${all.filter(x=>x.status==="needs_followup").length}</div></div></div><div class="card" style="margin-top:13px"><input id="search" style="width:100%;padding:12px;border:1px solid #ccd6df;border-radius:10px" placeholder="${T("search")}"><div id="members" class="list" style="margin-top:12px"></div></div>`;const draw=()=>{const q=(document.querySelector("#search").value||"").toLowerCase();document.querySelector("#members").innerHTML=all.filter(x=>[x.full_name,x.dxn_member_id,x.whatsapp].join(" ").toLowerCase().includes(q)).map(x=>`<div class="item"><div class="row between"><b>${esc(x.full_name)}</b><span class="pill">${esc(x.status)}</span></div><div class="small muted">${esc(x.dxn_member_id||"—")} · ${esc(x.whatsapp)}</div><div class="row" style="margin-top:8px"><a class="btn" target="_blank" href="https://wa.me/${String(x.whatsapp).replace(/\D/g,"")}">WhatsApp</a><button class="btn alt" onclick="changeStatus('${x.id}','active')">نشط</button><button class="btn alt" onclick="changeStatus('${x.id}','needs_followup')">متابعة</button></div></div>`).join("")||T("no")};document.querySelector("#search").oninput=draw;draw()}
window.changeStatus=async(id,status)=>{const {error}=await db.from("dxn_start_members").update({status}).eq("id",id);if(error)toast(error.message);else{toast(T("success"));adminPanel(document.querySelector("#panel"))}};
function render(){document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.querySelector("#langBtn").textContent=lang==="ar"?"FR":"AR";if(member)dashboard();else auth()}
if(db)db.auth.onAuthStateChange(()=>setTimeout(boot,0));boot();